name: GitHub Actions Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions: 
      id-token: write # This is required for requesting the OIDC JWT Token
      contents: read # Required when GH token is used to authenticate with private repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/azure-container-registry-login
      - name: Authenticate with ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ vars.ACR_ADMIN_USERNAME }}
          password: ${{ secrets.ACR_ADMIN_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          tags:  ${{ vars.ACR_LOGIN_SERVER }}/prod-blog-repo:app-${{ github.sha }}
      
  deploy:
    permissions:
      id-token: write # This is required for requesting the OIDC JWT Token
      contents: read # Required when GH token is used to authenticate with private repo
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ vars.ACR_ADMIN_USERNAME }}
          acrUsername: ${{ vars.ACR_ADMIN_USERNAME }}
          acrPassword: ${{ secrets.ACR_ADMIN_PASSWORD }}
          imageToDeploy: ${{ vars.ACR_LOGIN_SERVER }}/prod-blog-repo:app-${{ github.sha }}

    needs: build

      

      